# Generated by Django 5.0.7 on 2024-07-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='equip_s_vaz',
            new_name='equipVaz',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='lei_coer',
            new_name='leiCoer',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='mat_disp',
            new_name='matDisp',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='serv_exc',
            new_name='servExc',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='sist_ins',
            new_name='sistIns',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='am_agua',
            new_name='agua',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='ins_coe',
            new_name='insCoe',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='loc_memb',
            new_name='locMemb',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='material_int',
            new_name='matInt',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='pre_req_tec',
            new_name='preFlu',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='pre_trat_flush',
            new_name='preReq',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='pre_trat_op',
            new_name='preTrat',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='sis_seg',
            new_name='sisSeg',
        ),
        migrations.RenameField(
            model_name='start',
            old_name='valv_aliv',
            new_name='valv',
        ),
    ]
