# Generated by Django 5.0.7 on 2024-07-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catback', '0002_rename_equip_s_vaz_servicos_equipvaz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressurizador',
            old_name='func_correto',
            new_name='funcionamentoCorreto',
        ),
        migrations.RenameField(
            model_name='pressurizador',
            old_name='press_alimentacao',
            new_name='pressaoAlimentacao',
        ),
    ]
