# Generated by Django 5.0.7 on 2024-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catback', '0003_rename_func_correto_pressurizador_funcionamentocorreto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='const_lei',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='osmose',
            name='teste_agua',
            field=models.CharField(blank=True, choices=[('Funcionamento Correto', 'Funcionamento Correto'), ('Apresenta Defeito', 'Apresenta Defeito'), ('na', 'N/A')], default='Selecione', max_length=25),
        ),
        migrations.AlterField(
            model_name='osmose',
            name='teste_press',
            field=models.CharField(blank=True, choices=[('Funcionamento Correto', 'Funcionamento Correto'), ('Apresenta Defeito', 'Apresenta Defeito'), ('na', 'N/A')], default='Selecione', max_length=25),
        ),
    ]
